import type { Language } from "./src/i18n"

type AnimeItem = {
  titleZh: string
  titleEn: string
  titleJa: string
  score: number
}

type Data = {
  [key: string]: AnimeItem[]
}

const data: Data = {
  "院线1": [
    { titleZh: "西游记之大圣归来", titleEn: "Shirobako", titleJa: "SHIROBAKO", score: 8.7 },
    { titleZh: "熊出没之雪岭熊风", titleEn: "Shirobako", titleJa: "SHIROBAKO", score: 8.7 },
    {
      titleZh: "大鱼海棠",
      titleEn: "Fate/stay night [Unlimited Blade Works]",
      titleJa: "Fate/stay night [Unlimited Blade Works]",
      score: 7.5,
    },
    {
      titleZh: "熊出没之熊心归来",
      titleEn: "No Game No Life",
      titleJa: "ノーゲーム・ノーライフ",
      score: 7.7,
    },
    {
      titleZh: "小门神",
      titleEn: "Ping Pong",
      titleJa: "ピンポン THE ANIMATION",
      score: 8.7,
    },
    {
      titleZh: "熊出没·奇幻空间",
      titleEn: "Amagi Brilliant Park",
      titleJa: "甘城ブリリアントパーク",
      score: 7,
    },
    {
      titleZh: "大护法",
      titleEn: "Parasyte -the maxim-",
      titleJa: "寄生獣 セイの格率",
      score: 8,
    },
    { titleZh: "熊出没·变形记", titleEn: "Nisekoi", titleJa: "ニセコイ", score: 7.1 },
    {
      titleZh: "风语咒",
      titleEn: "Monthly Girls' Nozaki-kun",
      titleJa: "月刊少女野崎くん",
      score: 7.8,
    },
    {
      titleZh: "昨日青空",
      titleEn: "Is the Order a Rabbit?",
      titleJa: "ご注文はうさぎですか？",
      score: 7.3,
    },
    {
      titleZh: "哪吒之魔童降世",
      titleEn: "Akame ga Kill!",
      titleJa: "アカメが斬る！",
      score: 6.6,
    },
    {
      titleZh: "白蛇：缘起",
      titleEn: "Space Dandy",
      titleJa: "スペース☆ダンディ",
      score: 8,
    },
  ],
   "院线2": [
    { titleZh: "熊出没·原始时代", titleEn: "Shirobako", titleJa: "SHIROBAKO", score: 8.7 },
    { titleZh: "罗小黑战记", titleEn: "Shirobako", titleJa: "SHIROBAKO", score: 8.7 },
    {
      titleZh: "全职高手之巅峰荣耀",
      titleEn: "Fate/stay night [Unlimited Blade Works]",
      titleJa: "Fate/stay night [Unlimited Blade Works]",
      score: 7.5,
    },
    {
      titleZh: "姜子牙",
      titleEn: "No Game No Life",
      titleJa: "ノーゲーム・ノーライフ",
      score: 7.7,
    },
    {
      titleZh: "熊出没·狂野大陆",
      titleEn: "Ping Pong",
      titleJa: "ピンポン THE ANIMATION",
      score: 8.7,
    },
    {
      titleZh: "白蛇2：青蛇劫起",
      titleEn: "Amagi Brilliant Park",
      titleJa: "甘城ブリリアントパーク",
      score: 7,
    },
    {
      titleZh: "雄狮少年",
      titleEn: "Parasyte -the maxim-",
      titleJa: "寄生獣 セイの格率",
      score: 8,
    },
    { titleZh: "俑之城", titleEn: "Nisekoi", titleJa: "ニセコイ", score: 7.1 },
    {
      titleZh: "新神榜：哪吒重生",
      titleEn: "Monthly Girls' Nozaki-kun",
      titleJa: "月刊少女野崎くん",
      score: 7.8,
    },
    {
      titleZh: "熊出没·重返地球",
      titleEn: "Is the Order a Rabbit?",
      titleJa: "ご注文はうさぎですか？",
      score: 7.3,
    },
    {
      titleZh: "新神榜：杨戬",
      titleEn: "Akame ga Kill!",
      titleJa: "アカメが斬る！",
      score: 6.6,
    },
    {
      titleZh: "长安三万里",
      titleEn: "Space Dandy",
      titleJa: "スペース☆ダンディ",
      score: 8,
    },
  ],
 "院线3": [
    { titleZh: "熊出没·伴我熊芯", titleEn: "Shirobako", titleJa: "SHIROBAKO", score: 8.7 },
    { titleZh: "深海", titleEn: "Shirobako", titleJa: "SHIROBAKO", score: 8.7 },
    {
      titleZh: "熊出没·逆转时空",
      titleEn: "Fate/stay night [Unlimited Blade Works]",
      titleJa: "Fate/stay night [Unlimited Blade Works]",
      score: 7.5,
    },
    {
      titleZh: "白蛇：浮生",
      titleEn: "No Game No Life",
      titleJa: "ノーゲーム・ノーライフ",
      score: 7.7,
    },
    {
      titleZh: "雄狮少年2",
      titleEn: "Ping Pong",
      titleJa: "ピンポン THE ANIMATION",
      score: 8.7,
    },
    {
      titleZh: "哪吒之魔童闹海",
      titleEn: "Amagi Brilliant Park",
      titleJa: "甘城ブリリアントパーク",
      score: 7,
    },
    {
      titleZh: "浪浪山小妖怪",
      titleEn: "Parasyte -the maxim-",
      titleJa: "寄生獣 セイの格率",
      score: 8,
    },
    { titleZh: "熊出没·重启未来", titleEn: "Nisekoi", titleJa: "ニセコイ", score: 7.1 },
    {
      titleZh: "罗小黑战记2",
      titleEn: "Monthly Girls' Nozaki-kun",
      titleJa: "月刊少女野崎くん",
      score: 7.8,
    },
    {
      titleZh: "时间之子",
      titleEn: "Is the Order a Rabbit?",
      titleJa: "ご注文はうさぎですか？",
      score: 7.3,
    },
    {
      titleZh: "聊斋：兰若寺",
      titleEn: "Akame ga Kill!",
      titleJa: "アカメが斬る！",
      score: 6.6,
    },
    {
      titleZh: "八仙！",
      titleEn: "Space Dandy",
      titleJa: "スペース☆ダンディ",
      score: 8,
    },
  ],
   "院线1": [
    { titleZh: "三国第一部争洛阳", titleEn: "Shirobako", titleJa: "SHIROBAKO", score: 8.7 },
    { titleZh: "去你的岛", titleEn: "Shirobako", titleJa: "SHIROBAKO", score: 8.7 },
    {
      titleZh: "三国的星空",
      titleEn: "Fate/stay night [Unlimited Blade Works]",
      titleJa: "Fate/stay night [Unlimited Blade Works]",
      score: 7.5,
    },
    {
      titleZh: "熊出没·年年有熊",
      titleEn: "No Game No Life",
      titleJa: "ノーゲーム・ノーライフ",
      score: 7.7,
    },
     ],
  "2015": [
    {
      titleZh: "那年那兔那些事",
      titleEn: "Saekano: How to Raise a Boring Girlfriend",
      titleJa: "冴えない彼女の育てかた",
      score: 7.2,
    },
    {
      titleZh: "勇者大冒险",
      titleEn: "Assassination Classroom",
      titleJa: "暗殺教室",
      score: 7.3,
    },
    {
      titleZh: "狐妖小红娘下沙篇",
      titleEn: "One Punch Man",
      titleJa: "ワンパンマン",
      score: 8,
    },
    {
      titleZh: "黑白无双",
      titleEn: "The Testament of Sister New Devil",
      titleJa: "新妹魔王の契約者",
      score: 5.8,
    },
    {
      titleZh: "茶啊二中2",
      titleEn: "Charlotte",
      titleJa: "シャーロット",
      score: 6.3,
    },
    {
      titleZh: "画江湖之灵主",
      titleEn: "Overlord",
      titleJa: "オーバーロード",
      score: 6.9,
    },
    {
      titleZh: "疯味英雄",
      titleEn: "Prison School",
      titleJa: "監獄学園",
      score: 7.3,
    },
    {
      titleZh: "超神学院3",
      titleEn: "Plastic Memories",
      titleJa: "プラスティック・メモリーズ",
      score: 7,
    },
      {
      titleZh: "雏蜂",
      titleEn: "Plastic Memories",
      titleJa: "プラスティック・メモリーズ",
      score: 7,
    },
      {
      titleZh: "择天记",
      titleEn: "Plastic Memories",
      titleJa: "プラスティック・メモリーズ",
      score: 7,
    },
      {
      titleZh: "中国惊奇先生",
      titleEn: "Plastic Memories",
      titleJa: "プラスティック・メモリーズ",
      score: 7,
    },
        {
      titleZh: "墓王之王",
      titleEn: "Plastic Memories",
      titleJa: "プラスティック・メモリーズ",
      score: 7,
    },
  ],
  "2016": [
    {
      titleZh: "狐妖小红娘王权篇",
      titleEn: "Kono Suba",
      titleJa: "この素晴らしい世界に祝福を！",
      score: 7.6,
    },
    {
      titleZh: "天行九歌",
      titleEn: "March Comes in Like a Lion",
      titleJa: "3月のライオン",
      score: 8.3,
    },
    { titleZh: "勇者大冒险2", titleEn: "ReLIFE", titleJa: "ReLIFE", score: 7.7 },
    {
      titleZh: "纳米核心2",
      titleEn: "The Disastrous Life of Saiki K.",
      titleJa: "斉木楠雄のΨ難",
      score: 7.7,
    },
    {
      titleZh: "超神学院 黑甲",
      titleEn: "Re:Zero ",
      titleJa: "Re:ゼロから始める異世界生活",
      score: 7.4,
    },
    {
      titleZh: "镇魂街",
      titleEn: "Erased",
      titleJa: "僕だけがいない街",
      score: 7.7,
    },
    {
      titleZh: "我的三体 罗辑传",
      titleEn: "Mob Psycho 100",
      titleJa: "モブサイコ100",
      score: 7.8,
    },
    {
      titleZh: "狐妖小红娘 月红篇",
      titleEn: "Grimgar of Fantasy and Ash",
      titleJa: "灰と幻想のグリムガル",
      score: 7.5,
    },
    {
      titleZh: "茶啊二中3",
      titleEn: "This Art Club Has a Problem!",
      titleJa: "この美術部には問題がある！",
      score: 7.3,
    },
    {
      titleZh: "凸变英雄BABA",
      titleEn: "Flip Flappers",
      titleJa: "フリップフラッパーズ",
      score: 7.5,
    },
    {
      titleZh: "一人之下",
      titleEn: "Flip Flappers",
      titleJa: "フリップフラッパーズ",
      score: 7.5,
    },
    {
      titleZh: "全职法师",
      titleEn: "Flip Flappers",
      titleJa: "フリップフラッパーズ",
      score: 7.5,
    },
  ],
  "2017": [
    {
      titleZh: "少年锦衣卫",
      titleEn: "Girls' Last Tour",
      titleJa: "少女終末旅行",
      score: 8.1,
    },
    {
      titleZh: "狐妖小红娘 千颜篇",
      titleEn: "Made in Abyss",
      titleJa: "メイドインアビス",
      score: 8.2,
    },
    {
      titleZh: "快把我哥带走",
      titleEn: "Miss Kobayashi's Dragon Maid",
      titleJa: "小林さんちのメイドラゴン",
      score: 7.4,
    },
    {
      titleZh: "全职高手",
      titleEn: "Kakegurui",
      titleJa: "賭ケグルイ",
      score: 7,
    },
    {
      titleZh: "中国唱诗班",
      titleEn: "WorldEnd",
      titleJa: "終末なにしてますか？忙しいですか？救ってもらっていいですか？",
      score: 7.6,
    },
    {
      titleZh: "我是江小白",
      titleEn: "Tsuki ga Kirei",
      titleJa: "月がきれい",
      score: 7.9,
    },
    {
      titleZh: "星学院III 潘朵拉秘境",
      titleEn: "Sagrada Reset",
      titleJa: "サクラダリセット",
      score: 7.9,
    },
    {
      titleZh: "一人之下 第二季",
      titleEn: "BanG Dream!",
      titleJa: "BanG Dream!",
      score: 6.4,
    },
    {
      titleZh: "画江湖之不良人 第二季",
      titleEn: "Saga of Tanya the Evil",
      titleJa: "幼女戦記",
      score: 7.2,
    },
    {
      titleZh: "少年锦衣卫",
      titleEn: "Little Witch Academia",
      titleJa: "リトルウィッチアカデミア",
      score: 7.7,
    },
      {
      titleZh: "雄兵连",
      titleEn: "Little Witch Academia",
      titleJa: "リトルウィッチアカデミア",
      score: 7.7,
    },
    {
      titleZh: "我的天劫女友",
      titleEn: "Little Witch Academia",
      titleJa: "リトルウィッチアカデミア",
      score: 7.7,
    },
  ],
  "2018": [
    {
      titleZh: "迷域行者",
      titleEn: "Yuru Camp△",
      titleJa: "ゆるキャン△",
      score: 8.2,
    },
    {
      titleZh: "茶啊二中4",
      titleEn: "Grand Blue",
      titleJa: "ぐらんぶる",
      score: 7.8,
    },
    {
      titleZh: "非人哉",
      titleEn: "Umamusume Pretty Derby",
      titleJa: "ウマ娘 プリティーダービー",
      score: 7,
    },
    {
      titleZh: "刺客伍六七",
      titleEn: "Violet Evergarden",
      titleJa: "ヴァイオレット・エヴァーガーデン",
      score: 7.5,
    },
    {
      titleZh: "魔道祖师 前尘篇",
      titleEn: "Run with the Wind",
      titleJa: "風が強く吹いている",
      score: 8.3,
    },
    {
      titleZh: "侠肝义胆沈剑心",
      titleEn: "Shoujo☆Kageki Revue Starlight",
      titleJa: "少女☆歌劇 レヴュースタァライト",
      score: 7.9,
    },
    {
      titleZh: "0号宿舍",
      titleEn: "Teasing Master Takagi-san",
      titleJa: "からかい上手の高木さん",
      score: 7.5,
    },
    {
      titleZh: "星辰变",
      titleEn: "Zombie Land Saga",
      titleJa: "ゾンビランドサガ",
      score: 7.8,
    },
    {
      titleZh: "画江湖之不良人3",
      titleEn: "A Place Further Than the Universe",
      titleJa: "宇宙よりも遠い場所",
      score: 8.2,
    },
    {
      titleZh: "少年歌行",
      titleEn: "Rascal Does Not Dream of Bunny Girl Senpai",
      titleJa: "青春ブタ野郎はバニーガール先輩の夢を見ない",
      score: 7.4,
    },
    {
      titleZh: "西行纪",
      titleEn: "Goblin Slayer",
      titleJa: "ゴブリンスレイヤー",
      score: 6.7,
    },
    {
      titleZh: "通灵妃",
      titleEn: "Bloom into You",
      titleJa: "やがて君になる",
      score: 7.8,
    },
  ],
  "2019": [
    {
      titleZh: "凹凸世界3",
      titleEn: "Vinland Saga",
      titleJa: "ヴィンランド・サガ",
      score: 8.3,
    },
    {
      titleZh: "狐妖小红娘 竹业篇",
      titleEn: "Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunōsen",
      titleJa: "かぐや様は告らせたい～天才たちの恋愛頭脳戦～",
      score: 7.8,
    },
    {
      titleZh: "灵笼",
      titleEn: "The Demon Girl Next Door",
      titleJa: "まちカドまぞく",
      score: 7.5,
    },
    {
      titleZh: "斗破苍穹3",
      titleEn: "Demon Slayer",
      titleJa: "鬼滅の刃",
      score: 7.3,
    },
    {
      titleZh: "汉化日记",
      titleEn: "Fire Force",
      titleJa: "炎炎ノ消防隊",
      score: 6.5,
    },
    {
      titleZh: "万国志",
      titleEn: "Wasteful Days of High School Girls",
      titleJa: "女子高生の無駄づかい",
      score: 7.6,
    },
    {
      titleZh: "伍六七2 最强发型师",
      titleEn: "Cautious Hero: ",
      titleJa: "慎重勇者～この勇者が俺TUEEEくせに慎重すぎる～",
      score: 6.9,
    },
    {
      titleZh: "斗罗大陆",
      titleEn: "Angels' 3Piece!",
      titleJa: "私に天使が舞い降りた！",
      score: 7.3,
    },
    {
      titleZh: "我家大师兄脑子有坑",
      titleEn: "Boogiepop and Others",
      titleJa: "ブギーポップは笑わない",
      score: 7.3,
    },
    {
      titleZh: "请吃红小豆吧",
      titleEn: "How Clumsy You Are, Miss Ueno",
      titleJa: "上野さんは不器用",
      score: 6.5,
    },
      {
      titleZh: "猫妖的诱惑",
      titleEn: "How Clumsy You Are, Miss Ueno",
      titleJa: "上野さんは不器用",
      score: 6.5,
    },
      {
      titleZh: "武动乾坤",
      titleEn: "How Clumsy You Are, Miss Ueno",
      titleJa: "上野さんは不器用",
      score: 6.5,
    },
  ],
  "2020": [
    {
      titleZh: "我的三体 章北海传",
      titleEn: "Ishuzoku Reviewers",
      titleJa: "異種族レビュアーズ",
      score: 7.7,
    },
    {
      titleZh: "万圣街",
      titleEn: "Wandering Witch: The Journey of Elaina",
      titleJa: "魔女の旅々",
      score: 7.1,
    },
    {
      titleZh: "大理寺日志",
      titleEn: "Adachi and Shimamura",
      titleJa: "安達としまむら",
      score: 7.3,
    },
    {
      titleZh: "狐妖小红娘 金晨曦篇",
      titleEn: "ID:INVADED",
      titleJa: "ID:INVADED イド：インヴェイデッド",
      score: 7.5,
    },
    {
      titleZh: "天宝伏妖录",
      titleEn: "Keep Your Hands Off Eizouken!",
      titleJa: "映像研には手を出すな！",
      score: 8.1,
    },
    {
      titleZh: "有药",
      titleEn: "Jujutsu Kaisen",
      titleJa: "呪術廻戦",
      score: 7.1,
    },
    {
      titleZh: "雾山五行",
      titleEn: "Tonikawa: Over the Moon For You",
      titleJa: "トニカクカワイイ",
      score: 6.3,
    },
    {
      titleZh: "凡人修仙传",
      titleEn: "Kakushigoto",
      titleJa: "かくしごと",
      score: 7.7,
    },
    {
      titleZh: "灵笼 特别篇",
      titleEn: "In/Spectre",
      titleJa: "虚構推理",
      score: 6.3,
    },
    {
      titleZh: "汉化日记2",
      titleEn: "Koisuru Asteroid",
      titleJa: "恋する小惑星",
      score: 6.9,
    },
    {
      titleZh: "天官赐福",
      titleEn: "Our Last Crusade or the Rise of a New World",
      titleJa: "キミと僕の最後の戦場、あるいは世界が始まる聖戦",
      score: 5.5,
    },
    {
      titleZh: "元龙",
      titleEn: "Dropkick on My Devil!",
      titleJa: "邪神ちゃんドロップキック’",
      score: 7.3,
    },
    {
      titleZh: "仙王的日常生活",
      titleEn: "My Next Life as a Villainess: All Routes Lead to Doom!",
      titleJa: "乙女ゲームの破滅フラグしかない悪役令嬢に転生してしまった…",
      score: 6.5,
    },
    {
      titleZh: "百妖谱",
      titleEn: "Sleepy Princess in the Demon Castle",
      titleJa: "魔王城でおやすみ",
      score: 7,
    },
    {
      titleZh: "一念永恒",
      titleEn: "Rent-A-Girlfriend",
      titleJa: "彼女、お借りします",
      score: 5.8,
    },
      {
      titleZh: "穿书自救指南",
      titleEn: "Rent-A-Girlfriend",
      titleJa: "彼女、お借りします",
      score: 5.8,
    },
  ],
  "2021": [
    {
      titleZh: "风灵玉秀",
      titleEn: "86 -Eighty-Six-",
      titleJa: "86―エイティシックス―",
      score: 7.6,
    },
    {
      titleZh: "伍六七3 玄武国篇",
      titleEn: "Mushoku Tensei: Jobless Reincarnation",
      titleJa: "無職転生 ～異世界行ったら本気だす～",
      score: 7.9,
    },
    {
      titleZh: "枕刀歌",
      titleEn: "Redo of Healer",
      titleJa: "回復術士のやり直し",
      score: 6.2,
    },
    {
      titleZh: "罗小黑战记 众生之门篇",
      titleEn: "Odd Taxi",
      titleJa: "オッドタクシー",
      score: 8.5,
    },
    {
      titleZh: "画江湖之不良人4",
      titleEn: "I’ve Been Killing Slimes for 300 Years and Maxed Out My Level",
      titleJa: "スライム倒して300年、知らないうちにレベルMAXになってました",
      score: 6.3,
    },
    {
      titleZh: "时光代理人",
      titleEn: "Sonny Boy",
      titleJa: "Sonny Boy",
      score: 7.8,
    },
    {
      titleZh: "眷思量",
      titleEn: "Horimiya",
      titleJa: "ホリミヤ",
      score: 6.8,
    },
    {
      titleZh: "魔道祖师3 完结篇",
      titleEn: "Combatants Will Be Dispatched!",
      titleJa: "戦闘員、派遣します！",
      score: 6.3,
    },
    {
      titleZh: "烈火浇愁",
      titleEn: "Komi Can't Communicate",
      titleJa: "古見さんは、コミュ症です。",
      score: 7,
    },
    {
      titleZh: "斗破苍穹 三年之约",
      titleEn: "Wonder Egg Priority",
      titleJa: "ワンダーエッグ・プライオリティ",
      score: 6.8,
    },
    {
      titleZh: "紫川",
      titleEn: "Remake Our Life!",
      titleJa: "ぼくたちのリメイク",
      score: 6.4,
    },
    {
      titleZh: "完美世界",
      titleEn: "Mieruko-chan",
      titleJa: "見える子ちゃん",
      score: 6.8,
    },
    {
      titleZh: "吞噬星空",
      titleEn: "The Dungeon of Black Company",
      titleJa: "迷宮ブラックカンパニー",
      score: 6.7,
    },
  ],
  "2022": [
    {
      titleZh: "画江湖之不良人5",
      titleEn: "Bocchi the Rock!",
      titleJa: "ぼっち・ざ・ろっく！",
      score: 8.4,
    },
    {
      titleZh: "侠肝义胆沈剑心3上",
      titleEn: "Lycoris Recoil",
      titleJa: "リコリス・リコイル",
      score: 6.3,
    },
    {
      titleZh: "苍兰诀",
      titleEn: "The Eminence in Shadow",
      titleJa: "陰の実力者になりたくて！",
      score: 7.1,
    },
    {
      titleZh: "百妖谱3",
      titleEn: "Summer Time Rendering",
      titleJa: "サマータイムレンダ",
      score: 7.5,
    },
    {
      titleZh: "黑门",
      titleEn: "Uncle from Another World",
      titleJa: "異世界おじさん",
      score: 7.6,
    },
    {
      titleZh: "两不疑2",
      titleEn: "My Dress-Up Darling",
      titleJa: "その着せ替え人形は恋をする",
      score: 7.2,
    },
    {
      titleZh: "血与心",
      titleEn: "Call of the Night",
      titleJa: "よふかしのうた",
      score: 7.4,
    },
    {
      titleZh: "神印王座",
      titleEn: "Aharen Is Indecipherable",
      titleJa: "阿波連さんははかれない",
      score: 6.4,
    },
     {
      titleZh: "千从狩",
      titleEn: "Aharen Is Indecipherable",
      titleJa: "阿波連さんははかれない",
      score: 6.4,
    },
    {
      titleZh: "永生",
      titleEn: "SPY×FAMILY",
      titleJa: "SPY×FAMILY",
      score: 7.2,
    },
    {
      titleZh: "大王饶命",
      titleEn: "Immoral Guild",
      titleJa: "不徳のギルド",
      score: 7.1,
    },
    {
      titleZh: "少年白马醉春风",
      titleEn: "Chainsaw Man",
      titleJa: "チェンソーマン",
      score: 6.9,
    },
  ],
  "2023": [
    {
      titleZh: "中国奇谭",
      titleEn: "Frieren: Beyond Journey's End",
      titleJa: "葬送のフリーレン",
      score: 8.5,
    },
    {
      titleZh: "有兽焉",
      titleEn: "The Apothecary Diaries",
      titleJa: "薬屋のひとりごと",
      score: 7.5,
    },
    {
      titleZh: "火凤燎原",
      titleEn: "BanG Dream! It's MyGO!!!!!",
      titleJa: "BanG Dream! It's MyGO!!!!!",
      score: 8.1,
    },
    {
      titleZh: "沧元图",
      titleEn: "The Dangers in My Heart",
      titleJa: "僕の心のヤバイやつ",
      score: 7.8,
    },
    {
      titleZh: "有药2",
      titleEn: "The 100 Girlfriends Who Really Love You",
      titleJa: "君のことが大大大大大好きな100人の彼女",
      score: 7.3,
    },
    {
      titleZh: "凡人修仙传 年番2",
      titleEn: "Onimai: I'm Now Your Sister!",
      titleJa: "お兄ちゃんはおしまい！",
      score: 7.6,
    },
    {
      titleZh: "枕刀歌2",
      titleEn: "Skip and Loafer",
      titleJa: "スキップとローファー",
      score: 7.7,
    },
    {
      titleZh: "命运拳台",
      titleEn: "Pokémon Horizons",
      titleJa: "ポケットモンスター 地平線",
      score: 7.5,
    },
    {
      titleZh: "三体",
      titleEn: "Shangri-La Frontier",
      titleJa: "シャングリラ・フロンティア ～クソゲーハンター、神ゲーに挑む～",
      score: 6.4,
    },
    {
      titleZh: "师兄啊师兄",
      titleEn: "KamiKatsu: Working for God in a Godless World",
      titleJa: "神無き世界のカミサマ活動",
      score: 6.8,
    },
    {
      titleZh: "镖人",
      titleEn: "Oshi no Ko",
      titleJa: "【推しの子】",
      score: 7.4,
    },
    {
      titleZh: "仙逆",
      titleEn: "Heavenly Delusion",
      titleJa: "天国大魔境",
      score: 7.8,
    },
    {
      titleZh: "遮天",
      titleEn: "Farming Life in Another World",
      titleJa: "異世界のんびり農家",
      score: 6.4,
    },
    {
      titleZh: "第一序列",
      titleEn: "Farming Life in Another World",
      titleJa: "異世界のんびり農家",
      score: 6.4,
    },
  ],
  "2024": [
    {
      titleZh: "咸鱼哥2",
      titleEn: "Too Many Losing Heroines!",
      titleJa: "負けヒロインが多すぎる！",
      score: 8,
    },
    {
      titleZh: "诛仙2",
      titleEn: "GIRLS BAND CRY",
      titleJa: "ガールズバンドクライ",
      score: 7.6,
    },
    {
      titleZh: "反派初始化",
      titleEn: "Dandadan",
      titleJa: "ダンダダン",
      score: 7.5,
    },
    {
      titleZh: "眷思量2",
      titleEn: "Gimai Seikatsu",
      titleJa: "義妹生活",
      score: 7.3,
    },
    {
      titleZh: "成何体统",
      titleEn: "Delicious in Dungeon",
      titleJa: "ダンジョン飯",
      score: 7.8,
    },
    {
      titleZh: "茶啊二中5",
      titleEn: "Solo Leveling",
      titleJa: "俺だけレベルアップな件",
      score: 6.5,
    },
    {
      titleZh: "斩神之凡尘神域",
      titleEn: "Shoshimin",
      titleJa: "小市民シリーズ",
      score: 6.1,
    },
    {
      titleZh: "赘婿2",
      titleEn: "Gushing over Magical Girls",
      titleJa: "魔法少女にあこがれて",
      score: 7,
    },
    { titleZh: "剑来", titleEn: "Blue Box", titleJa: "青の箱", score: 6.8 },
    {
      titleZh: "大道朝天",
      titleEn: "2.5 Dimensional Seduction",
      titleJa: "2.5次元の誘惑",
      score: 6.7,
    },
    {
      titleZh: "牧神记",
      titleEn: "Orb: On the Movements of the Earth",
      titleJa: "地球の運動について",
      score: 6.2,
    },
    {
      titleZh: "笼中人",
      titleEn: "Oblivion Battery",
      titleJa: "忘却バッテリー",
      score: 7.9,
    },
    {
      titleZh: "今天的晚餐就是你",
      titleEn: "Alya Sometimes Hides Her Feelings in Russian",
      titleJa: "時々ボソッとロシア語でデレる隣のアーリャさん",
      score: 5.6,
    },
  ],
  "2025": [
    {
      titleZh: "火凤燎原2",
      titleEn: "GNOSIA",
      titleJa: "グノーシア",
      score: 7.5,
    },
    {
      titleZh: "灵笼2",
      titleEn: "Chitose Is in the Ramune Bottle",
      titleJa: "千歳くんはラムネ瓶のなか",
      score: 4.1,
    },
    {
      titleZh: "诡秘之主",
      titleEn: "There's No Freaking Way I'll be Your Lover! Unless...",
      titleJa:
        "わたしが恋人になれるわけないじゃん、ムリムリ！（※ムリじゃなかった!?）",
      score: 7.4,
    },
    {
      titleZh: "苍兰诀2",
      titleEn: "Medalist",
      titleJa: "メダリスト",
      score: 8,
    },
    {
      titleZh: "百妖谱5",
      titleEn: "Ruri Rocks",
      titleJa: "瑠璃の宝石",
      score: 8.1,
    },
    {
      titleZh: "枕刀歌3",
      titleEn: "Apocalypse Hotel",
      titleJa: "アポカリプスホテル",
      score: 8.2,
    },
    {
      titleZh: "深潜 强制倒带",
      titleEn: "Nukitashi THE ANIMATION",
      titleJa: "ぬきたし THE ANIMATION",
      score: 6.7,
    },
    {
      titleZh: "诛仙3",
      titleEn: "Food for the Soul",
      titleJa: "日々は過ぎれど飯うまし",
      score: 7.7,
    },
    {
      titleZh: "神国之上",
      titleEn: "Tojima Tanzaburo Wants to Be a Masked Rider",
      titleJa: "東島丹三郎は仮面ライダーになりたい",
      score: 6.9,
    },
    {
      titleZh: "凸变英雄X",
      titleEn: "The Fragrant Flower Blooms with Dignity",
      titleJa: "薫る花は凛と咲く",
      score: 7,
    },
    {
      titleZh: "时光代理人 英都篇",
      titleEn: "Uma Musume Cinderella Gray",
      titleJa: "ウマ娘 シンデレラグレイ",
      score: 7.5,
    },
    {
      titleZh: "仙王的日常生活5",
      titleEn: "Gachiakuta",
      titleJa: "ガチアクタ",
      score: 6.2,
    },
  ],
    "2026": [
    {
      titleZh: "中国奇谭2",
      titleEn: "GNOSIA",
      titleJa: "グノーシア",
      score: 7.5,
    },
    {
      titleZh: "剑来2",
      titleEn: "Chitose Is in the Ramune Bottle",
      titleJa: "千歳くんはラムネ瓶のなか",
      score: 4.1,
    },
    {
      titleZh: "成何体统2",
      titleEn: "There's No Freaking Way I'll be Your Lover! Unless...",
      titleJa:
        "わたしが恋人になれるわけないじゃん、ムリムリ！（※ムリじゃなかった!?）",
      score: 7.4,
    },
    {
      titleZh: "择天记3D",
      titleEn: "Medalist",
      titleJa: "メダリスト",
      score: 8,
    },
    {
      titleZh: "将夜",
      titleEn: "Ruri Rocks",
      titleJa: "瑠璃の宝石",
      score: 8.1,
    },
    {
      titleZh: "放开那个女巫",
      titleEn: "Apocalypse Hotel",
      titleJa: "アポカリプスホテル",
      score: 8.2,
    },
    {
      titleZh: "镖人2",
      titleEn: "Nukitashi THE ANIMATION",
      titleJa: "ぬきたし THE ANIMATION",
      score: 6.7,
    },
    {
      titleZh: "百日成王",
      titleEn: "Food for the Soul",
      titleJa: "日々は過ぎれど飯うまし",
      score: 7.7,
    },
    {
      titleZh: "记忆管理局",
      titleEn: "Tojima Tanzaburo Wants to Be a Masked Rider",
      titleJa: "東島丹三郎は仮面ライダーになりたい",
      score: 6.9,
    },
    {
      titleZh: "茶啊二中6",
      titleEn: "The Fragrant Flower Blooms with Dignity",
      titleJa: "薫る花は凛と咲く",
      score: 7,
    },
    {
      titleZh: "斩神2",
      titleEn: "Uma Musume Cinderella Gray",
      titleJa: "ウマ娘 シンデレラグレイ",
      score: 7.5,
    },
  ],
}

// 添加一个辅助函数来根据语言获取动画标题
export const getAnimeTitle = (anime: AnimeItem, language: Language): string => {
  return anime[
    ("title" +
      language.charAt(0).toUpperCase() +
      language.slice(1)) as keyof AnimeItem
  ] as string
}

export default data
